### ISSUE TITLE
Reply with Class Section

### ISSUE THREAD

**Issue by ProfRojas** [donieypon/Team8#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by donieypon** [comment]
Hello Professor, my team is in class section 05.

**Comment by huantran98** [comment]
Hello Professor!

**Comment by ProfRojas** [comment]
Please have your teammates respond. Otherwise, you will only receive partial credit for the GitHub portion.

**Comment by thayash1** [comment]
Hello professor

**Comment by YenniLamb** [comment]
Hello professor

**Comment by ProfRojas** [comment]
Thanks!
